import { TIMER_SESSION_VERSION, timerId } from './timerDomain';
import type { TimerSession } from './timerTypes';
export type TimerScope = { instanceKey: string; userId: number };
const sessionBase = 'redmine_canvas_gantt_timer_session'; const prefsBase = 'redmine_canvas_gantt_timer_preferences'; const tabBase = 'redmine_canvas_gantt_timer_tab_id';
const suffix = (scope: TimerScope) => `${encodeURIComponent(scope.instanceKey)}:user:${scope.userId}`;
export const keysFor = (scope: TimerScope) => ({ session: `${sessionBase}:${suffix(scope)}`, preferences: `${prefsBase}:${suffix(scope)}`, lock: `redmine_canvas_gantt_timer_lock:${suffix(scope)}` });
export function getTabId() { try { const old = sessionStorage.getItem(tabBase); if (old) return old; const next = timerId(); sessionStorage.setItem(tabBase, next); return next; } catch { return `kanban-${timerId()}`; } }
export function isTimerSession(value: unknown): value is TimerSession { const x = value as Partial<TimerSession> | null; return !!x && x.version === TIMER_SESSION_VERSION && typeof x.sessionId === 'string' && Number.isInteger(x.revision) && (x.revision ?? 0) > 0 && Array.isArray(x.segments) && ['running', 'expired', 'stopped_pending_record'].includes(String(x.state)); }
export function load(scope: TimerScope): TimerSession | null { try { const raw = localStorage.getItem(keysFor(scope).session); const value: unknown = raw ? JSON.parse(raw) : null; return isTimerSession(value) ? value : null; } catch { return null; } }
async function lock<T>(scope: TimerScope, fn: () => T): Promise<T> { const name = keysFor(scope).lock; if (navigator.locks?.request) return navigator.locks.request(name, { mode: 'exclusive' }, fn); const leaseKey = name; const owner = getTabId(); const deadline = Date.now() + 2000; for (let retries = 0; retries < 20; retries += 1) { try { const existing = JSON.parse(localStorage.getItem(leaseKey) || 'null') as { owner?: string; until?: number } | null; if (!existing || !existing.until || existing.until < Date.now() || existing.owner === owner) { localStorage.setItem(leaseKey, JSON.stringify({ owner, until: deadline })); const claimed = JSON.parse(localStorage.getItem(leaseKey) || 'null'); if (claimed?.owner === owner) { try { return fn(); } finally { localStorage.removeItem(leaseKey); } } } } catch { return fn(); } await new Promise((resolve) => setTimeout(resolve, 10)); } return fn(); }
export async function mutate(scope: TimerScope, updater: (session: TimerSession | null) => TimerSession | null | undefined): Promise<{ session: TimerSession | null; applied: boolean }> { return lock(scope, () => { const current = load(scope); const next = updater(current); if (next === undefined) return { session: current, applied: false }; try { const key = keysFor(scope).session; if (next === null) localStorage.removeItem(key); else localStorage.setItem(key, JSON.stringify({ ...next, revision: (current?.revision ?? 0) + 1, updatedAt: Date.now() })); return { session: next === null ? null : load(scope), applied: true }; } catch { return { session: current, applied: false }; } }); }
