import type { TimerIntervalMinutes, TimerRecordingPhase, TimerSegment, TimerSession } from './timerTypes';
export const TIMER_SESSION_VERSION = 4;
export const timerId = () => typeof crypto !== 'undefined' && crypto.randomUUID ? crypto.randomUUID() : `timer_${Date.now()}_${Math.random().toString(36).slice(2)}`;
export function createTimerSession(issueId: number, subject: string, minutes: TimerIntervalMinutes, autoStop: boolean, userId: number, now = Date.now()): TimerSession { return { version: TIMER_SESSION_VERSION, sessionId: timerId(), revision: 1, issueId, subject, autoStop, deadlineAt: now + minutes * 60000, segments: [{ startedAt: now }], state: 'running', userId, createdAt: now, updatedAt: now }; }
export function elapsed(session: TimerSession, now = Date.now()) { return session.segments.reduce((total, segment) => total + Math.max(0, (segment.stoppedAt ?? now) - segment.startedAt), 0); }
export function remaining(session: TimerSession, now = Date.now()) { return session.state === 'stopped_pending_record' || !session.deadlineAt ? 0 : Math.max(0, session.deadlineAt - now); }
export function recordedHours(session: TimerSession) { return (Math.round(elapsed(session) / 36000) / 100).toFixed(2); }
export function tick(session: TimerSession, now = Date.now()): TimerSession { if (session.state !== 'running' || !session.deadlineAt || now < session.deadlineAt) return session; if (!session.autoStop) return { ...session, state: 'expired', updatedAt: now }; const segments = session.segments.map((segment, index) => index === session.segments.length - 1 && !segment.stoppedAt ? { ...segment, stoppedAt: session.deadlineAt } : segment); return { ...session, state: 'stopped_pending_record', segments, updatedAt: now }; }
export function stop(session: TimerSession, now = Date.now()): TimerSession { if (session.state === 'stopped_pending_record') return session; const segments: TimerSegment[] = session.segments.map((segment, index) => index === session.segments.length - 1 && !segment.stoppedAt ? { ...segment, stoppedAt: now } : segment); return { ...session, state: 'stopped_pending_record', segments, updatedAt: now }; }
export function extend(session: TimerSession, minutes: TimerIntervalMinutes, now = Date.now()): TimerSession { if (session.recordingAttempt) return session; if (session.state === 'stopped_pending_record') return { ...session, state: 'running', segments: [...session.segments, { startedAt: now }], deadlineAt: now + minutes * 60000, updatedAt: now }; return { ...session, state: 'running', deadlineAt: (session.state === 'running' ? session.deadlineAt ?? now : now) + minutes * 60000, updatedAt: now }; }
export function beginRecording(session: TimerSession, ownerTabId: string, now = Date.now()): TimerSession | undefined { if (session.state !== 'stopped_pending_record' || session.recordingAttempt) return undefined; return { ...session, recordingAttempt: { id: timerId(), ownerTabId, openedAt: now, phase: 'editing' }, updatedAt: now }; }
export function transitionRecording(session: TimerSession, attemptId: string, phase: TimerRecordingPhase): TimerSession | undefined { if (!session.recordingAttempt || session.recordingAttempt.id !== attemptId) return undefined; return { ...session, recordingAttempt: { ...session.recordingAttempt, phase }, updatedAt: Date.now() }; }
export function clearRecording(session: TimerSession, attemptId: string): TimerSession | undefined { if (!session.recordingAttempt || session.recordingAttempt.id !== attemptId) return undefined; const next = { ...session }; delete next.recordingAttempt; return { ...next, updatedAt: Date.now() }; }
