import React, { useEffect, useState } from 'react';
import type { Issue } from '../types';
import { TIMER_INTERVAL_MINUTES } from './timerTypes';
import type { TimerIntervalMinutes, TimerRecordingContext, TimerSession } from './timerTypes';

type Props = { labels: Record<string, string>; session: TimerSession | null; startIssue: Issue | null; autoStop: boolean; onCloseStart: () => void; onStart: (minutes: TimerIntervalMinutes, autoStop: boolean) => void; onExtend: (minutes: TimerIntervalMinutes) => void; onStop: () => void; onRecord: () => void; onResolveUnknown: (resolution: 'recorded' | 'unregistered') => void };
const duration = (milliseconds: number) => { const seconds = Math.floor(Math.max(0, milliseconds) / 1000); return `${String(Math.floor(seconds / 3600)).padStart(2, '0')}:${String(Math.floor(seconds / 60) % 60).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`; };
export function GlobalTimer({ labels, session, onExtend, onStop, onRecord, onResolveUnknown }: Omit<Props, 'startIssue' | 'autoStop' | 'onCloseStart' | 'onStart'>) { const [, update] = useState(0); useEffect(() => { if (!session || session.state === 'stopped_pending_record') return; const id = setInterval(() => update(value => value + 1), 1000); return () => clearInterval(id); }, [session]); if (!session) return null; const now = Date.now(); const elapsed = session.segments.reduce((total, part) => total + Math.max(0, (part.stoppedAt ?? now) - part.startedAt), 0); const remaining = session.deadlineAt ? Math.max(0, session.deadlineAt - now) : 0; const unknown = session.recordingAttempt?.phase === 'unknown'; return <aside className="rk-work-timer" aria-label={labels.work_timer ?? 'Work timer'}><strong>{session.subject}</strong><span>{labels.timer_elapsed ?? 'Elapsed'} {duration(elapsed)}</span>{unknown ? <><span>{labels.timer_unknown ?? 'Could not confirm whether work time was recorded.'}</span><button type="button" onClick={() => onResolveUnknown('recorded')}>{labels.timer_mark_recorded ?? 'Mark recorded'}</button><button type="button" onClick={() => onResolveUnknown('unregistered')}>{labels.timer_reenter ?? 'Re-enter'}</button></> : <>{session.state !== 'stopped_pending_record' ? <span>{labels.timer_remaining ?? 'Remaining'} {duration(remaining)}</span> : <span>{labels.timer_pending ?? 'Work time not recorded'}</span>} {session.state !== 'stopped_pending_record' ? <><button type="button" onClick={onStop}>{labels.timer_stop ?? 'Stop'}</button>{TIMER_INTERVAL_MINUTES.map(minutes => <button key={minutes} type="button" onClick={() => onExtend(minutes)}>+{minutes}</button>)}</> : <button type="button" onClick={onRecord}>{labels.timer_record ?? 'Record work time'}</button>}</>}</aside>; }
export function TimerStartModal({ labels, startIssue, autoStop: initialAutoStop, onCloseStart, onStart }: Pick<Props, 'labels' | 'startIssue' | 'autoStop' | 'onCloseStart' | 'onStart'>) { const [minutes, setMinutes] = useState<TimerIntervalMinutes>(30); const [autoStop, setAutoStop] = useState(initialAutoStop); useEffect(() => setAutoStop(initialAutoStop), [initialAutoStop, startIssue?.id]); if (!startIssue) return null; return <div className="rk-modal-backdrop" role="dialog" aria-modal="true"><div className="rk-work-timer-modal"><h2>{labels.timer_start ?? 'Start work timer'}</h2><p>#{startIssue.id} {startIssue.subject}</p><select aria-label={labels.timer_duration ?? 'Duration'} value={minutes} onChange={event => setMinutes(Number(event.target.value) as TimerIntervalMinutes)}>{TIMER_INTERVAL_MINUTES.map(value => <option key={value} value={value}>{value} min</option>)}</select><label><input type="checkbox" checked={autoStop} onChange={event => setAutoStop(event.target.checked)} /> {labels.timer_auto_stop ?? 'Stop automatically at the selected time'}</label><div><button type="button" onClick={onCloseStart}>{labels.cancel ?? 'Cancel'}</button><button type="button" className="rk-btn-primary" onClick={() => onStart(minutes, autoStop)}>{labels.timer_start ?? 'Start work timer'}</button></div></div></div>; }
export type { TimerRecordingContext };
